import type { ComponentDefinition } from "@/lib/engine/types";
import { P } from "./helpers";

const G = "Optics";

export const OPTICS_DEFINITIONS: ComponentDefinition[] = [
  {
    type: "laser",
    label: "Laser",
    category: "physics",
    group: G,
    description: "Emits a single narrow monochromatic beam along its axis. Rotate to aim.",
    size: { width: 110, height: 34 },
    visual: { archetype: "laser" },
    roles: ["light-emitter"],
    properties: [P.toggle("on", "On", "Optics"), P.select("color", "Wavelength", [["red", "Red 650 nm"], ["green", "Green 532 nm"], ["blue", "Blue 450 nm"], ["violet", "Violet 405 nm"], ["white", "White (polychromatic)"]], "Optics")],
    defaults: { on: true, color: "red" },
  },
  {
    type: "light-source",
    label: "Light source",
    category: "physics",
    group: G,
    description: "Lamp producing a parallel or diverging bundle of white rays (acts as the object).",
    size: { width: 80, height: 90 },
    visual: { archetype: "lightsource" },
    roles: ["light-emitter"],
    properties: [P.toggle("on", "On", "Optics"), P.select("beam", "Beam", [["parallel", "Parallel"], ["divergent", "Point source (diverging)"]], "Optics"), P.slider("rays", "Number of rays", 1, 15, 1, "", "Optics"), P.slider("spread", "Spread angle", 2, 60, 1, "°", "Optics")],
    defaults: { on: true, beam: "divergent", rays: 7, spread: 16 },
  },
  {
    type: "convex-lens",
    label: "Convex lens",
    category: "physics",
    group: G,
    description: "Converging thin lens: 1/f = 1/u + 1/v.",
    size: { width: 26, height: 140 },
    visual: { archetype: "lens", variant: "convex" },
    roles: ["optical"],
    properties: [P.number("focalLength", "Focal length f", "cm", 1, 200, 0.5, "Optics")],
    defaults: { focalLength: 10 },
  },
  {
    type: "concave-lens",
    label: "Concave lens",
    category: "physics",
    group: G,
    description: "Diverging thin lens (negative focal length).",
    size: { width: 26, height: 140 },
    visual: { archetype: "lens", variant: "concave" },
    roles: ["optical"],
    properties: [P.number("focalLength", "Focal length |f|", "cm", 1, 200, 0.5, "Optics")],
    defaults: { focalLength: 10 },
  },
  {
    type: "mirror",
    label: "Mirror",
    category: "physics",
    group: G,
    description: "Reflects rays: angle of incidence = angle of reflection.",
    size: { width: 14, height: 140 },
    visual: { archetype: "mirror" },
    roles: ["optical"],
    properties: [P.select("mirrorType", "Type", [["plane", "Plane"], ["concave", "Concave"], ["convex", "Convex"]], "Optics"), P.number("focalLength", "Focal length", "cm", 1, 200, 0.5, "Optics")],
    defaults: { mirrorType: "plane", focalLength: 15 },
  },
  {
    type: "prism",
    label: "Prism",
    category: "physics",
    group: G,
    description: "Triangular glass prism — refracts and disperses white light into a spectrum.",
    size: { width: 120, height: 104 },
    visual: { archetype: "prism" },
    roles: ["optical"],
    properties: [P.slider("refractiveIndex", "Refractive index n", 1, 2.5, 0.01, "", "Optics")],
    defaults: { refractiveIndex: 1.52 },
  },
  {
    type: "glass-block",
    label: "Glass block",
    category: "physics",
    group: G,
    description: "Rectangular block for measuring angles of refraction (Snell's law).",
    size: { width: 160, height: 100 },
    visual: { archetype: "glass-block" },
    roles: ["optical"],
    properties: [P.slider("refractiveIndex", "Refractive index n", 1, 2.5, 0.01, "", "Optics")],
    defaults: { refractiveIndex: 1.5 },
    keywords: ["refraction", "snell"],
  },
  {
    type: "screen",
    label: "Screen",
    category: "physics",
    group: G,
    description: "White screen that catches rays to show where an image forms.",
    size: { width: 12, height: 160 },
    visual: { archetype: "screen" },
    roles: ["optical"],
    properties: [],
    defaults: {},
  },
  {
    type: "optical-bench",
    label: "Optical bench",
    category: "physics",
    group: G,
    description: "Graduated rail (cm) for aligning optical components on a common axis.",
    size: { width: 900, height: 36 },
    visual: { archetype: "bench" },
    roles: ["support"],
    properties: [],
    defaults: {},
  },
];
