import type { SafetyLevel } from "@/lib/engine/types";

export type ChemCategory =
  | "element"
  | "acid"
  | "base"
  | "salt"
  | "metal"
  | "non-metal"
  | "organic"
  | "inorganic"
  | "indicator"
  | "solvent"
  | "gas";

export const CHEM_CATEGORIES: { id: ChemCategory; label: string }[] = [
  { id: "element", label: "Elements" },
  { id: "acid", label: "Acids" },
  { id: "base", label: "Bases" },
  { id: "salt", label: "Salts" },
  { id: "metal", label: "Metals" },
  { id: "non-metal", label: "Non-metals" },
  { id: "organic", label: "Organic" },
  { id: "inorganic", label: "Inorganic" },
  { id: "indicator", label: "Indicators" },
  { id: "solvent", label: "Solvents" },
  { id: "gas", label: "Gases" },
];

export type PhysicalState = "solid" | "liquid" | "gas" | "aqueous";
export type ChemicalForm = "solution" | "solid" | "liquid" | "gas";

export interface Hazard {
  level: SafetyLevel;
  pictograms: string[];
  statement: string;
  ppe: string[];
}

export interface Chemical {
  id: string;
  name: string;
  formula: string;
  categories: ChemCategory[];
  state: PhysicalState;
  form: ChemicalForm; // how it is dispensed by default
  molarMass: number; // g/mol
  density: number; // g/mL (of the dispensed form)
  defaultConcentration?: number; // mol/L for solutions
  soluble?: boolean;
  color?: string; // colour of the solution / solid
  colorStrength?: number; // mol/L at which the colour is fully saturated
  acid?: { protons: number; Ka?: number }; // Ka omitted → strong acid
  base?: { hydroxides: number; Kb?: number }; // Kb omitted → strong base
  conjugate?: string; // conjugate base/acid id (buffers)
  indicator?: string; // indicator model id
  flammable?: boolean;
  oxidizer?: boolean;
  hazard: Hazard;
  description: string;
}

const PPE_BASIC = ["Safety goggles", "Lab coat"];
const PPE_CORROSIVE = ["Safety goggles", "Nitrile gloves", "Lab coat"];
const PPE_TOXIC = ["Safety goggles", "Nitrile gloves", "Lab coat", "Fume hood"];

const safe = (statement = "Low hazard in the concentrations used."): Hazard => ({
  level: "safe",
  pictograms: [],
  statement,
  ppe: PPE_BASIC,
});
const irritant = (statement: string, ppe = PPE_CORROSIVE): Hazard => ({
  level: "caution",
  pictograms: ["Irritant"],
  statement,
  ppe,
});
const corrosive = (statement: string, level: SafetyLevel = "caution"): Hazard => ({
  level,
  pictograms: ["Corrosive"],
  statement,
  ppe: PPE_CORROSIVE,
});

export const CHEMICALS: Chemical[] = [
  /* ---------------- Solvents ---------------- */
  {
    id: "h2o",
    name: "Distilled water",
    formula: "H2O",
    categories: ["solvent", "inorganic"],
    state: "liquid",
    form: "liquid",
    molarMass: 18.015,
    density: 1.0,
    hazard: safe("Non-hazardous."),
    description: "Purified water used as the universal laboratory solvent.",
  },
  {
    id: "ethanol",
    name: "Ethanol",
    formula: "C2H5OH",
    categories: ["organic", "solvent"],
    state: "liquid",
    form: "liquid",
    molarMass: 46.07,
    density: 0.789,
    flammable: true,
    hazard: { level: "caution", pictograms: ["Flammable"], statement: "Highly flammable liquid and vapour. Keep away from open flames.", ppe: PPE_BASIC },
    description: "Common organic solvent and fuel.",
  },
  {
    id: "methanol",
    name: "Methanol",
    formula: "CH3OH",
    categories: ["organic", "solvent"],
    state: "liquid",
    form: "liquid",
    molarMass: 32.04,
    density: 0.792,
    flammable: true,
    hazard: { level: "danger", pictograms: ["Flammable", "Toxic"], statement: "Highly flammable. Toxic if swallowed, inhaled or absorbed through skin.", ppe: PPE_TOXIC },
    description: "Simplest alcohol; toxic solvent.",
  },
  {
    id: "acetone",
    name: "Acetone",
    formula: "C3H6O",
    categories: ["organic", "solvent"],
    state: "liquid",
    form: "liquid",
    molarMass: 58.08,
    density: 0.784,
    flammable: true,
    hazard: { level: "caution", pictograms: ["Flammable", "Irritant"], statement: "Highly flammable; vapours may cause drowsiness.", ppe: PPE_BASIC },
    description: "Volatile ketone solvent.",
  },
  {
    id: "hexane",
    name: "Hexane",
    formula: "C6H14",
    categories: ["organic", "solvent"],
    state: "liquid",
    form: "liquid",
    molarMass: 86.18,
    density: 0.655,
    flammable: true,
    hazard: { level: "danger", pictograms: ["Flammable", "Health hazard"], statement: "Highly flammable; neurotoxic on prolonged exposure.", ppe: PPE_TOXIC },
    description: "Non-polar solvent, immiscible with water.",
  },

  /* ---------------- Acids ---------------- */
  {
    id: "hcl",
    name: "Hydrochloric acid",
    formula: "HCl",
    categories: ["acid", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 36.46,
    density: 1.02,
    defaultConcentration: 1,
    soluble: true,
    acid: { protons: 1 },
    hazard: corrosive("Causes severe skin burns and eye damage; irritating vapours."),
    description: "Strong monoprotic mineral acid.",
  },
  {
    id: "h2so4",
    name: "Sulfuric acid",
    formula: "H2SO4",
    categories: ["acid", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 98.08,
    density: 1.06,
    defaultConcentration: 1,
    soluble: true,
    acid: { protons: 2 },
    hazard: corrosive("Causes severe burns. Dilution is strongly exothermic — always add acid to water.", "danger"),
    description: "Strong diprotic acid and dehydrating agent.",
  },
  {
    id: "hno3",
    name: "Nitric acid",
    formula: "HNO3",
    categories: ["acid", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 63.01,
    density: 1.03,
    defaultConcentration: 1,
    soluble: true,
    acid: { protons: 1 },
    oxidizer: true,
    hazard: { level: "danger", pictograms: ["Corrosive", "Oxidizer"], statement: "Strong oxidiser and corrosive; releases toxic NO₂ fumes.", ppe: PPE_TOXIC },
    description: "Strong oxidising mineral acid.",
  },
  {
    id: "ch3cooh",
    name: "Acetic acid",
    formula: "CH3COOH",
    categories: ["acid", "organic"],
    state: "aqueous",
    form: "solution",
    molarMass: 60.05,
    density: 1.01,
    defaultConcentration: 1,
    soluble: true,
    acid: { protons: 1, Ka: 1.8e-5 },
    conjugate: "ch3coona",
    hazard: irritant("Causes skin and eye irritation at higher concentrations."),
    description: "Weak organic acid (vinegar).",
  },
  {
    id: "h3po4",
    name: "Phosphoric acid",
    formula: "H3PO4",
    categories: ["acid", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 97.99,
    density: 1.05,
    defaultConcentration: 1,
    soluble: true,
    acid: { protons: 1, Ka: 7.5e-3 },
    hazard: corrosive("Causes skin burns and eye damage."),
    description: "Weak triprotic acid (first dissociation modelled).",
  },

  /* ---------------- Bases ---------------- */
  {
    id: "naoh",
    name: "Sodium hydroxide",
    formula: "NaOH",
    categories: ["base", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 40.0,
    density: 1.04,
    defaultConcentration: 1,
    soluble: true,
    base: { hydroxides: 1 },
    hazard: corrosive("Causes severe skin burns and eye damage."),
    description: "Strong base (caustic soda).",
  },
  {
    id: "koh",
    name: "Potassium hydroxide",
    formula: "KOH",
    categories: ["base", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 56.11,
    density: 1.05,
    defaultConcentration: 1,
    soluble: true,
    base: { hydroxides: 1 },
    hazard: corrosive("Causes severe skin burns and eye damage."),
    description: "Strong base (caustic potash).",
  },
  {
    id: "caoh2",
    name: "Calcium hydroxide (limewater)",
    formula: "Ca(OH)2",
    categories: ["base", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 74.09,
    density: 1.0,
    defaultConcentration: 0.02,
    soluble: true,
    base: { hydroxides: 2 },
    hazard: irritant("Causes serious eye irritation."),
    description: "Saturated limewater — used to test for CO₂.",
  },
  {
    id: "nh3",
    name: "Ammonia solution",
    formula: "NH3",
    categories: ["base", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 17.03,
    density: 0.99,
    defaultConcentration: 1,
    soluble: true,
    base: { hydroxides: 1, Kb: 1.8e-5 },
    conjugate: "nh4cl",
    hazard: { level: "caution", pictograms: ["Corrosive", "Irritant"], statement: "Pungent vapours irritate eyes and airways.", ppe: PPE_TOXIC },
    description: "Weak base, aqueous ammonia.",
  },
  {
    id: "na2co3",
    name: "Sodium carbonate",
    formula: "Na2CO3",
    categories: ["salt", "base", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 105.99,
    density: 1.05,
    defaultConcentration: 0.5,
    soluble: true,
    base: { hydroxides: 1, Kb: 2.1e-4 },
    hazard: irritant("Causes serious eye irritation."),
    description: "Washing soda; basic salt.",
  },
  {
    id: "nahco3",
    name: "Sodium bicarbonate",
    formula: "NaHCO3",
    categories: ["salt", "base", "inorganic"],
    state: "solid",
    form: "solid",
    molarMass: 84.01,
    density: 2.2,
    soluble: true,
    base: { hydroxides: 1, Kb: 2.3e-8 },
    hazard: safe(),
    description: "Baking soda; mild base.",
  },

  /* ---------------- Salts ---------------- */
  {
    id: "nacl",
    name: "Sodium chloride",
    formula: "NaCl",
    categories: ["salt", "inorganic"],
    state: "solid",
    form: "solid",
    molarMass: 58.44,
    density: 2.16,
    soluble: true,
    hazard: safe(),
    description: "Table salt.",
  },
  {
    id: "kcl",
    name: "Potassium chloride",
    formula: "KCl",
    categories: ["salt", "inorganic"],
    state: "solid",
    form: "solid",
    molarMass: 74.55,
    density: 1.98,
    soluble: true,
    hazard: safe(),
    description: "Ionic salt.",
  },
  {
    id: "agno3",
    name: "Silver nitrate",
    formula: "AgNO3",
    categories: ["salt", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 169.87,
    density: 1.01,
    defaultConcentration: 0.1,
    soluble: true,
    oxidizer: true,
    hazard: { level: "caution", pictograms: ["Corrosive", "Oxidizer", "Environmental"], statement: "Stains skin black; corrosive oxidiser; toxic to aquatic life.", ppe: PPE_CORROSIVE },
    description: "Reagent for halide ion tests.",
  },
  {
    id: "cuso4",
    name: "Copper(II) sulfate",
    formula: "CuSO4",
    categories: ["salt", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 159.61,
    density: 1.05,
    defaultConcentration: 0.5,
    soluble: true,
    color: "#1d8fe1",
    colorStrength: 0.4,
    hazard: { level: "caution", pictograms: ["Irritant", "Environmental"], statement: "Harmful if swallowed; irritant; very toxic to aquatic life.", ppe: PPE_CORROSIVE },
    description: "Blue transition-metal salt.",
  },
  {
    id: "kmno4",
    name: "Potassium permanganate",
    formula: "KMnO4",
    categories: ["salt", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 158.03,
    density: 1.0,
    defaultConcentration: 0.02,
    soluble: true,
    color: "#7e1fa0",
    colorStrength: 0.005,
    oxidizer: true,
    hazard: { level: "danger", pictograms: ["Oxidizer", "Harmful", "Environmental"], statement: "Strong oxidiser — may intensify fire; harmful if swallowed.", ppe: PPE_CORROSIVE },
    description: "Deep purple oxidising agent.",
  },
  {
    id: "k2cr2o7",
    name: "Potassium dichromate",
    formula: "K2Cr2O7",
    categories: ["salt", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 294.18,
    density: 1.0,
    defaultConcentration: 0.05,
    soluble: true,
    color: "#f07c12",
    colorStrength: 0.03,
    oxidizer: true,
    hazard: { level: "danger", pictograms: ["Toxic", "Oxidizer", "Health hazard"], statement: "Carcinogenic, toxic and a strong oxidiser.", ppe: PPE_TOXIC },
    description: "Orange oxidiser (simulation only).",
  },
  {
    id: "ki",
    name: "Potassium iodide",
    formula: "KI",
    categories: ["salt", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 166.0,
    density: 1.0,
    defaultConcentration: 0.5,
    soluble: true,
    hazard: safe(),
    description: "Soluble iodide salt.",
  },
  {
    id: "pbno32",
    name: "Lead(II) nitrate",
    formula: "Pb(NO3)2",
    categories: ["salt", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 331.2,
    density: 1.02,
    defaultConcentration: 0.1,
    soluble: true,
    hazard: { level: "danger", pictograms: ["Toxic", "Health hazard", "Environmental"], statement: "Toxic heavy-metal salt; may damage fertility.", ppe: PPE_TOXIC },
    description: "Lead salt used to demonstrate precipitation (virtual only).",
  },
  {
    id: "bacl2",
    name: "Barium chloride",
    formula: "BaCl2",
    categories: ["salt", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 208.23,
    density: 1.02,
    defaultConcentration: 0.1,
    soluble: true,
    hazard: { level: "caution", pictograms: ["Toxic"], statement: "Toxic if swallowed.", ppe: PPE_CORROSIVE },
    description: "Reagent for sulfate ion tests.",
  },
  {
    id: "fecl3",
    name: "Iron(III) chloride",
    formula: "FeCl3",
    categories: ["salt", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 162.2,
    density: 1.03,
    defaultConcentration: 0.1,
    soluble: true,
    color: "#d6a21e",
    colorStrength: 0.15,
    hazard: corrosive("Corrosive; causes serious eye damage."),
    description: "Yellow-brown iron salt.",
  },
  {
    id: "feso4",
    name: "Iron(II) sulfate",
    formula: "FeSO4",
    categories: ["salt", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 151.91,
    density: 1.03,
    defaultConcentration: 0.1,
    soluble: true,
    color: "#a7d7a0",
    colorStrength: 0.3,
    hazard: irritant("Harmful if swallowed; irritant."),
    description: "Pale green iron(II) salt.",
  },
  {
    id: "na2s2o3",
    name: "Sodium thiosulfate",
    formula: "Na2S2O3",
    categories: ["salt", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 158.11,
    density: 1.02,
    defaultConcentration: 0.2,
    soluble: true,
    hazard: safe(),
    description: "Used in the 'disappearing cross' reaction-rate experiment.",
  },
  {
    id: "naocl",
    name: "Sodium hypochlorite (bleach)",
    formula: "NaOCl",
    categories: ["salt", "inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 74.44,
    density: 1.1,
    defaultConcentration: 0.7,
    soluble: true,
    base: { hydroxides: 1, Kb: 3.3e-7 },
    oxidizer: true,
    color: "#eef7c8",
    colorStrength: 1,
    hazard: { level: "caution", pictograms: ["Corrosive", "Environmental"], statement: "Corrosive. Never mix with acids or ammonia — releases toxic gases.", ppe: PPE_CORROSIVE },
    description: "Household bleach oxidiser.",
  },
  {
    id: "nh4cl",
    name: "Ammonium chloride",
    formula: "NH4Cl",
    categories: ["salt", "inorganic"],
    state: "solid",
    form: "solid",
    molarMass: 53.49,
    density: 1.53,
    soluble: true,
    acid: { protons: 1, Ka: 5.6e-10 },
    hazard: irritant("Harmful if swallowed; eye irritant."),
    description: "Weakly acidic ammonium salt.",
  },
  {
    id: "caco3",
    name: "Calcium carbonate (marble chips)",
    formula: "CaCO3",
    categories: ["salt", "inorganic"],
    state: "solid",
    form: "solid",
    molarMass: 100.09,
    density: 2.71,
    soluble: false,
    color: "#f3f4f6",
    hazard: safe(),
    description: "Insoluble carbonate — reacts with acids releasing CO₂.",
  },
  {
    id: "cuo",
    name: "Copper(II) oxide",
    formula: "CuO",
    categories: ["inorganic"],
    state: "solid",
    form: "solid",
    molarMass: 79.55,
    density: 6.31,
    soluble: false,
    color: "#1f1f1f",
    hazard: irritant("Harmful if swallowed; toxic to aquatic life."),
    description: "Black basic oxide used for salt preparation.",
  },
  {
    id: "mno2",
    name: "Manganese(IV) oxide",
    formula: "MnO2",
    categories: ["inorganic"],
    state: "solid",
    form: "solid",
    molarMass: 86.94,
    density: 5.03,
    soluble: false,
    color: "#2b2b2b",
    hazard: irritant("Harmful if swallowed or inhaled."),
    description: "Black catalyst for decomposing hydrogen peroxide.",
  },
  {
    id: "h2o2",
    name: "Hydrogen peroxide",
    formula: "H2O2",
    categories: ["inorganic"],
    state: "aqueous",
    form: "solution",
    molarMass: 34.01,
    density: 1.01,
    defaultConcentration: 1,
    soluble: true,
    oxidizer: true,
    hazard: { level: "caution", pictograms: ["Oxidizer", "Corrosive"], statement: "Oxidiser; causes eye damage at higher concentrations.", ppe: PPE_CORROSIVE },
    description: "Decomposes into water and oxygen, catalysed by MnO₂.",
  },
  {
    id: "glucose",
    name: "Glucose",
    formula: "C6H12O6",
    categories: ["organic"],
    state: "solid",
    form: "solid",
    molarMass: 180.16,
    density: 1.54,
    soluble: true,
    hazard: safe(),
    description: "Simple sugar.",
  },

  /* ---------------- Metals & non-metals (elements) ---------------- */
  {
    id: "mg",
    name: "Magnesium ribbon",
    formula: "Mg",
    categories: ["element", "metal"],
    state: "solid",
    form: "solid",
    molarMass: 24.31,
    density: 1.74,
    soluble: false,
    color: "#c9ccd1",
    flammable: true,
    hazard: { level: "caution", pictograms: ["Flammable"], statement: "Flammable solid; burns with intense white light.", ppe: PPE_BASIC },
    description: "Reactive alkaline-earth metal.",
  },
  {
    id: "zn",
    name: "Zinc granules",
    formula: "Zn",
    categories: ["element", "metal"],
    state: "solid",
    form: "solid",
    molarMass: 65.38,
    density: 7.14,
    soluble: false,
    color: "#a7adb5",
    hazard: safe("Low hazard; zinc dust is flammable."),
    description: "Moderately reactive transition metal.",
  },
  {
    id: "fe",
    name: "Iron filings",
    formula: "Fe",
    categories: ["element", "metal"],
    state: "solid",
    form: "solid",
    molarMass: 55.85,
    density: 7.87,
    soluble: false,
    color: "#5b5f66",
    hazard: safe(),
    description: "Common transition metal.",
  },
  {
    id: "cu",
    name: "Copper turnings",
    formula: "Cu",
    categories: ["element", "metal"],
    state: "solid",
    form: "solid",
    molarMass: 63.55,
    density: 8.96,
    soluble: false,
    color: "#b8653a",
    hazard: safe(),
    description: "Unreactive reddish-brown metal.",
  },
  {
    id: "al",
    name: "Aluminium foil",
    formula: "Al",
    categories: ["element", "metal"],
    state: "solid",
    form: "solid",
    molarMass: 26.98,
    density: 2.7,
    soluble: false,
    color: "#d4d8dd",
    hazard: safe(),
    description: "Light reactive metal protected by an oxide layer.",
  },
  {
    id: "na",
    name: "Sodium metal",
    formula: "Na",
    categories: ["element", "metal"],
    state: "solid",
    form: "solid",
    molarMass: 22.99,
    density: 0.97,
    soluble: false,
    color: "#dfe3e8",
    flammable: true,
    hazard: { level: "danger", pictograms: ["Flammable", "Corrosive"], statement: "Reacts violently with water releasing flammable hydrogen.", ppe: [...PPE_CORROSIVE, "Face shield"] },
    description: "Highly reactive alkali metal stored under oil.",
  },
  {
    id: "s",
    name: "Sulfur",
    formula: "S",
    categories: ["element", "non-metal"],
    state: "solid",
    form: "solid",
    molarMass: 32.06,
    density: 2.07,
    soluble: false,
    color: "#f5d90a",
    hazard: safe("Combustible solid."),
    description: "Yellow non-metal.",
  },
  {
    id: "c",
    name: "Carbon (graphite)",
    formula: "C",
    categories: ["element", "non-metal"],
    state: "solid",
    form: "solid",
    molarMass: 12.01,
    density: 2.26,
    soluble: false,
    color: "#262626",
    hazard: safe(),
    description: "Graphite powder / electrodes.",
  },
  {
    id: "i2",
    name: "Iodine",
    formula: "I2",
    categories: ["element", "non-metal"],
    state: "solid",
    form: "solid",
    molarMass: 253.81,
    density: 4.93,
    soluble: false,
    color: "#4a2a4f",
    hazard: irritant("Harmful; causes skin and eye irritation.", PPE_TOXIC),
    description: "Purple-black halogen solid.",
  },

  /* ---------------- Indicators ---------------- */
  {
    id: "phenolphthalein",
    name: "Phenolphthalein",
    formula: "C20H14O4",
    categories: ["indicator", "organic"],
    state: "aqueous",
    form: "solution",
    molarMass: 318.32,
    density: 0.8,
    defaultConcentration: 0.003,
    soluble: true,
    indicator: "phenolphthalein",
    hazard: irritant("Suspected carcinogen in pure form.", PPE_BASIC),
    description: "Colourless in acid, pink above pH 8.2.",
  },
  {
    id: "methyl-orange",
    name: "Methyl orange",
    formula: "C14H14N3NaO3S",
    categories: ["indicator", "organic"],
    state: "aqueous",
    form: "solution",
    molarMass: 327.33,
    density: 1.0,
    defaultConcentration: 0.001,
    soluble: true,
    indicator: "methyl-orange",
    hazard: safe("Toxic if swallowed in large amounts."),
    description: "Red below pH 3.1, yellow above 4.4.",
  },
  {
    id: "universal-indicator",
    name: "Universal indicator",
    formula: "mixture",
    categories: ["indicator"],
    state: "aqueous",
    form: "solution",
    molarMass: 300,
    density: 0.9,
    defaultConcentration: 0.001,
    soluble: true,
    indicator: "universal",
    flammable: true,
    hazard: safe("Contains ethanol — flammable."),
    description: "Full-spectrum colour change from pH 0 to 14.",
  },
  {
    id: "bromothymol-blue",
    name: "Bromothymol blue",
    formula: "C27H28Br2O5S",
    categories: ["indicator", "organic"],
    state: "aqueous",
    form: "solution",
    molarMass: 624.38,
    density: 1.0,
    defaultConcentration: 0.001,
    soluble: true,
    indicator: "bromothymol-blue",
    hazard: safe(),
    description: "Yellow in acid, green neutral, blue in base.",
  },
  {
    id: "litmus",
    name: "Litmus solution",
    formula: "mixture",
    categories: ["indicator"],
    state: "aqueous",
    form: "solution",
    molarMass: 300,
    density: 1.0,
    defaultConcentration: 0.001,
    soluble: true,
    indicator: "litmus",
    hazard: safe(),
    description: "Red in acid, blue in base.",
  },

  /* ---------------- Gases & reaction products ---------------- */
  { id: "h2", name: "Hydrogen", formula: "H2", categories: ["gas", "element", "non-metal"], state: "gas", form: "gas", molarMass: 2.016, density: 0.00008, flammable: true, hazard: { level: "caution", pictograms: ["Flammable"], statement: "Extremely flammable gas — 'squeaky pop' test.", ppe: PPE_BASIC }, description: "Lightest gas." },
  { id: "o2", name: "Oxygen", formula: "O2", categories: ["gas", "element", "non-metal"], state: "gas", form: "gas", molarMass: 32.0, density: 0.0013, oxidizer: true, hazard: { level: "caution", pictograms: ["Oxidizer"], statement: "Supports combustion — relights a glowing splint.", ppe: PPE_BASIC }, description: "Diatomic oxidising gas." },
  { id: "co2", name: "Carbon dioxide", formula: "CO2", categories: ["gas", "inorganic"], state: "gas", form: "gas", molarMass: 44.01, density: 0.0018, hazard: safe("Asphyxiant in high concentration; turns limewater milky."), description: "Product of carbonate + acid reactions." },
  { id: "cl2", name: "Chlorine", formula: "Cl2", categories: ["gas", "element", "non-metal"], state: "gas", form: "gas", molarMass: 70.9, density: 0.0032, hazard: { level: "danger", pictograms: ["Toxic", "Oxidizer", "Environmental"], statement: "Toxic, greenish-yellow gas — fatal if inhaled.", ppe: PPE_TOXIC }, description: "Toxic halogen gas." },
  { id: "nh3g", name: "Ammonia gas", formula: "NH3", categories: ["gas", "inorganic"], state: "gas", form: "gas", molarMass: 17.03, density: 0.0007, hazard: { level: "caution", pictograms: ["Toxic", "Corrosive"], statement: "Pungent, toxic gas — turns damp red litmus blue.", ppe: PPE_TOXIC }, description: "Alkaline gas." },
  { id: "so2", name: "Sulfur dioxide", formula: "SO2", categories: ["gas", "inorganic"], state: "gas", form: "gas", molarMass: 64.07, density: 0.0026, hazard: { level: "danger", pictograms: ["Toxic", "Corrosive"], statement: "Toxic if inhaled.", ppe: PPE_TOXIC }, description: "Acidic, choking gas." },
  { id: "n2", name: "Nitrogen", formula: "N2", categories: ["gas", "element", "non-metal"], state: "gas", form: "gas", molarMass: 28.01, density: 0.00125, hazard: safe("Inert asphyxiant."), description: "Inert atmospheric gas." },

  /* ---------------- Products (also dispensable) ---------------- */
  { id: "nano3", name: "Sodium nitrate", formula: "NaNO3", categories: ["salt", "inorganic"], state: "aqueous", form: "solution", molarMass: 84.99, density: 1.02, defaultConcentration: 0.5, soluble: true, oxidizer: true, hazard: irritant("Oxidiser; eye irritant."), description: "Soluble nitrate salt." },
  { id: "kno3", name: "Potassium nitrate", formula: "KNO3", categories: ["salt", "inorganic"], state: "solid", form: "solid", molarMass: 101.1, density: 2.11, soluble: true, oxidizer: true, hazard: irritant("Oxidiser."), description: "Saltpetre." },
  { id: "na2so4", name: "Sodium sulfate", formula: "Na2SO4", categories: ["salt", "inorganic"], state: "aqueous", form: "solution", molarMass: 142.04, density: 1.03, defaultConcentration: 0.5, soluble: true, hazard: safe(), description: "Neutral salt." },
  { id: "cacl2", name: "Calcium chloride", formula: "CaCl2", categories: ["salt", "inorganic"], state: "solid", form: "solid", molarMass: 110.98, density: 2.15, soluble: true, hazard: irritant("Causes serious eye irritation."), description: "Hygroscopic salt." },
  { id: "mgcl2", name: "Magnesium chloride", formula: "MgCl2", categories: ["salt", "inorganic"], state: "aqueous", form: "solution", molarMass: 95.21, density: 1.02, defaultConcentration: 0.5, soluble: true, hazard: safe(), description: "Soluble salt." },
  { id: "zncl2", name: "Zinc chloride", formula: "ZnCl2", categories: ["salt", "inorganic"], state: "aqueous", form: "solution", molarMass: 136.3, density: 1.02, defaultConcentration: 0.5, soluble: true, hazard: corrosive("Corrosive."), description: "Soluble zinc salt." },
  { id: "znso4", name: "Zinc sulfate", formula: "ZnSO4", categories: ["salt", "inorganic"], state: "aqueous", form: "solution", molarMass: 161.47, density: 1.02, defaultConcentration: 0.5, soluble: true, hazard: irritant("Eye irritant."), description: "Colourless zinc salt." },
  { id: "alcl3", name: "Aluminium chloride", formula: "AlCl3", categories: ["salt", "inorganic"], state: "aqueous", form: "solution", molarMass: 133.34, density: 1.02, defaultConcentration: 0.5, soluble: true, hazard: corrosive("Corrosive."), description: "Soluble aluminium salt." },
  { id: "mgo", name: "Magnesium oxide", formula: "MgO", categories: ["inorganic", "base"], state: "solid", form: "solid", molarMass: 40.3, density: 3.58, soluble: false, color: "#fafafa", hazard: safe(), description: "White ash formed when magnesium burns." },
  { id: "licl", name: "Lithium chloride", formula: "LiCl", categories: ["salt", "inorganic"], state: "solid", form: "solid", molarMass: 42.39, density: 2.07, soluble: true, hazard: irritant("Harmful if swallowed."), description: "Gives a crimson flame test." },
  { id: "srcl2", name: "Strontium chloride", formula: "SrCl2", categories: ["salt", "inorganic"], state: "solid", form: "solid", molarMass: 158.53, density: 3.05, soluble: true, hazard: irritant("Causes serious eye damage."), description: "Gives a bright red flame test." },
  { id: "k2so4", name: "Potassium sulfate", formula: "K2SO4", categories: ["salt", "inorganic"], state: "aqueous", form: "solution", molarMass: 174.26, density: 1.03, defaultConcentration: 0.5, soluble: true, hazard: safe(), description: "Neutral salt." },
  { id: "mgso4", name: "Magnesium sulfate", formula: "MgSO4", categories: ["salt", "inorganic"], state: "aqueous", form: "solution", molarMass: 120.37, density: 1.03, defaultConcentration: 0.5, soluble: true, hazard: safe(), description: "Epsom salt." },
  { id: "mnso4", name: "Manganese(II) sulfate", formula: "MnSO4", categories: ["salt", "inorganic"], state: "aqueous", form: "solution", molarMass: 151.0, density: 1.03, defaultConcentration: 0.5, soluble: true, color: "#fbe7ee", colorStrength: 2, hazard: irritant("Harmful on prolonged exposure."), description: "Very pale pink salt." },
  { id: "fecl2", name: "Iron(II) chloride", formula: "FeCl2", categories: ["salt", "inorganic"], state: "aqueous", form: "solution", molarMass: 126.75, density: 1.03, defaultConcentration: 0.5, soluble: true, color: "#a7d7a0", colorStrength: 0.3, hazard: corrosive("Corrosive."), description: "Pale green iron(II) salt." },
  { id: "ch3coona", name: "Sodium acetate", formula: "CH3COONa", categories: ["salt", "organic"], state: "aqueous", form: "solution", molarMass: 82.03, density: 1.02, defaultConcentration: 0.5, soluble: true, base: { hydroxides: 1, Kb: 5.6e-10 }, conjugate: "ch3cooh", hazard: safe(), description: "Conjugate base of acetic acid." },
  { id: "agcl", name: "Silver chloride", formula: "AgCl", categories: ["salt", "inorganic"], state: "solid", form: "solid", molarMass: 143.32, density: 5.56, soluble: false, color: "#f8fafc", hazard: safe(), description: "White precipitate, darkens in light." },
  { id: "baso4", name: "Barium sulfate", formula: "BaSO4", categories: ["salt", "inorganic"], state: "solid", form: "solid", molarMass: 233.38, density: 4.5, soluble: false, color: "#ffffff", hazard: safe(), description: "Dense white precipitate." },
  { id: "pbi2", name: "Lead(II) iodide", formula: "PbI2", categories: ["salt", "inorganic"], state: "solid", form: "solid", molarMass: 461.01, density: 6.16, soluble: false, color: "#facc15", hazard: { level: "danger", pictograms: ["Toxic"], statement: "Toxic lead compound.", ppe: PPE_TOXIC }, description: "Bright yellow 'golden rain' precipitate." },
  { id: "cuoh2", name: "Copper(II) hydroxide", formula: "Cu(OH)2", categories: ["base", "inorganic"], state: "solid", form: "solid", molarMass: 97.56, density: 3.37, soluble: false, color: "#38bdf8", hazard: irritant("Harmful if swallowed."), description: "Pale blue gelatinous precipitate." },
  { id: "feoh3", name: "Iron(III) hydroxide", formula: "Fe(OH)3", categories: ["base", "inorganic"], state: "solid", form: "solid", molarMass: 106.87, density: 3.4, soluble: false, color: "#9a3412", hazard: safe(), description: "Rust-brown precipitate." },
  { id: "s-ppt", name: "Colloidal sulfur", formula: "S", categories: ["non-metal"], state: "solid", form: "solid", molarMass: 32.06, density: 2.07, soluble: false, color: "#fde68a", hazard: safe(), description: "Pale-yellow cloudiness." },
  { id: "hno3-aq", name: "Nitric acid (product)", formula: "HNO3", categories: ["acid"], state: "aqueous", form: "solution", molarMass: 63.01, density: 1.0, soluble: true, acid: { protons: 1 }, hazard: corrosive("Corrosive."), description: "Nitric acid produced in solution." },
];

const BY_ID = new Map(CHEMICALS.map((c) => [c.id, c]));

/** Characteristic flame-test colours of metal ions. */
export const FLAME_COLORS: Record<string, { ion: string; color: string; name: string }> = {
  Li: { ion: "Li⁺", color: "#dc2626", name: "crimson" },
  Na: { ion: "Na⁺", color: "#fbbf24", name: "bright yellow-orange" },
  K: { ion: "K⁺", color: "#c084fc", name: "lilac" },
  Ca: { ion: "Ca²⁺", color: "#ea580c", name: "brick red" },
  Sr: { ion: "Sr²⁺", color: "#ef4444", name: "red" },
  Ba: { ion: "Ba²⁺", color: "#a3e635", name: "apple green" },
  Cu: { ion: "Cu²⁺", color: "#14b8a6", name: "blue-green" },
};

const FLAME_ION: Record<string, keyof typeof FLAME_COLORS> = {
  licl: "Li", nacl: "Na", naoh: "Na", na2co3: "Na", nahco3: "Na", nano3: "Na", na2so4: "Na", naocl: "Na", na2s2o3: "Na", ch3coona: "Na",
  kcl: "K", koh: "K", ki: "K", kno3: "K", kmno4: "K", k2cr2o7: "K", k2so4: "K",
  cacl2: "Ca", caco3: "Ca", caoh2: "Ca", srcl2: "Sr", bacl2: "Ba", cuso4: "Cu", cuo: "Cu", cucl2: "Cu",
};

export function flameIon(chemId: string) {
  const k = FLAME_ION[chemId];
  return k ? FLAME_COLORS[k] : undefined;
}

export function getChemical(id: string): Chemical | undefined {
  return BY_ID.get(id);
}

/** Pretty-print a formula with Unicode subscripts: H2SO4 → H₂SO₄. */
export function prettyFormula(formula: string): string {
  const sub = "₀₁₂₃₄₅₆₇₈₉";
  return formula.replace(/(?<=[A-Za-z)\]])(\d+)/g, (m) => m.split("").map((d) => sub[Number(d)]).join(""));
}

export function chemLabel(id: string): string {
  const c = getChemical(id);
  return c ? prettyFormula(c.formula) : id;
}
